name: 🧪 End-to-end tests

inputs:
  url:
    required: false
    type: string
  auth-bypass-token:
    required: false
    type: string
  public-store-domain:
    required: true
  public-storefront-api-token:
    required: true
  session-secret:
    required: true

runs:
  using: 'composite'
  steps:
    - name: 📥 Install dependencies
      shell: 'bash'
      # Changed from 'npm ci' to handle peer dependency conflicts faster
      run: npm install --legacy-peer-deps

    - name: 📦 Build
      shell: 'bash'
      run: npm run build
      env:
        PUBLIC_STORE_DOMAIN: ${{ inputs.public-store-domain }}
        PUBLIC_STOREFRONT_API_TOKEN: ${{ inputs.public-storefront-api-token }}
        # Fixed: using inputs.session-secret instead of secrets.session-secret
        SESSION_SECRET: ${{ inputs.session-secret }}

    - name: 💾 Turbo cache
      id: turbo-cache
      uses: actions/cache@v3
      with:
        path: |
          node_modules/.cache/turbo
          **/.turbo
        key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: |
          turbo-${{ github.job }}-${{ github.ref_name }}-

    - name: 📄 Get installed Playwright version
      shell: 'bash'
      run: echo "PLAYWRIGHT_VERSION=$(npm ls @playwright/test | grep @playwright -m 1 | sed 's/.*@//')" >> $GITHUB_ENV

    - name: 💾 Cache Playwright binaries
      uses: actions/cache@v3
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

    - name: 💽 Install Playwright Browsers (all)
      shell: 'bash'
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps chromium

    - name: 💽 Install Playwright (only system deps)
      shell: 'bash'
      if: steps.playwright-cache.outputs.cache-hit == 'true'
      run: npx playwright install-deps chromium

    - name: 🍄 Run Playwright tests
      shell: 'bash'
      run: |
        URL=${{ inputs.url }} \
        AUTH_BYPASS_TOKEN=${{ inputs.auth-bypass-token }} \
        PUBLIC_STORE_DOMAIN=${{ inputs.public-store-domain }} \
        PUBLIC_STOREFRONT_API_TOKEN=${{ inputs.public-storefront-api-token }} \
        SESSION_SECRET=${{ inputs.session-secret }} \
        npx playwright test

    - name: 🗒 Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: ./playwright-report/
        retention-days: 30
